# -*- coding: utf-8 -*-
"""Fourier_B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12SctMYU3Vj_7Vk20WqCu0L9feqp1y58A
"""

import numpy as np

from sympy import *

a, b, c, t = symbols('a b c t')
A,B,C=0.47333333333333333, -0.414769487313794, 0.03576593567901777

w=pi

expr=(a*t**2+b*t+c -(A+B*cos(w*t)+C*cos(2*w*t)))*t**2
expr2=(a*t**2+b*t+c -(A+B*cos(w*t)+C*cos(2*w*t)))*t
expr3=(a*t**2+b*t+c -(A+B*cos(w*t)+C*cos(2*w*t)))*1

sol1=integrate (expr,(t, -1, 1))
sol2=integrate (expr2,(t, -1, 1))
sol3=integrate (expr3,(t, -1, 1))

print('Exp1: ', sol1)
print('Exp2: ', sol2)
print('Exp3: ', sol3)

eqn=[
          Eq(sol1,0),
          Eq(sol2,0),
          Eq(sol3,0)
]

print(solve(eqn))

