# -*- coding: utf-8 -*-
"""Fourier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1umdjM0YJ39uiG9FsNGujTGNkVbXxl_pK
"""

import numpy as np

import matplotlib.pyplot as plt

from scipy.integrate import quad

T = 2
w=2*np.pi/T
p=1.420

def f(t):
  return (p*t**2)

def fa0(t):
  return f(t)
a0 = 1/T*quad(fa0, -1, 1)[0]

def fa1(t):
  return f(t)*np.cos(w*(p*t**2))
a1 = 2/T*quad(fa1, -1, 1)[0]

def fa2(t):
  return f(t)*np.cos(2*w*(p*t**2))
a2 = 2/T*quad(fa2, -1, 1)[0]

def fb1(t):
  return f(t)*np.sin(np.pi*(p*t**2))
b1 = 2/T*quad(fb1, -1, 1)[0]

def fb2(t):
  return f(t)*np.sin(2*np.pi*(p*t**2))
b2 = 2/T*quad(fb2, -1, 1)[0]

def F(t):
  return a0+a1*np.cos(w*(p*t**2))+a2*np.cos(2*w*(p*t**2))

print("a0 = ", a0)
print("a1 = ", a1)
print("a2 = ", a2)
print("b1 = ", b1)
print("b2 = ", b2)

t=np.linspace(-1, 1,100)
fig, ax = plt.subplots()
ax.plot(t,f(t),t,F(t))
ax.grid(True)
plt.show()